### ISSUE TITLE
Feature/bug: Navigating between landing page and launched iSEE app

### ISSUE THREAD

**Issue by lee-t** [iSEE/iSEEindex#59]
When you launch an iSEE app, there doesn't seem to be a way to get back to the landing page and select another config. In-browser, navigating `back` from an individual instance is disabled in firefox, and brings the user back to google start page in chrome. 

The only way to get back to the landing page is by reloading the app. I'm not sure if this is the intended method.

I would suggest either: a) a way to navigate between the landing page and the launched iSEE app or b) a in-app button to reload the app ie a button to trigger`session$reload()`

**Comment by kevinrue** [comment]
>  I'm not sure if this is the intended method.

Yes it is.

I'm curious to look into the `session$reload()` but 1) this is more an `iSEE` issue, 2) I'm not sure if it has any real benefit over reloading the app.
